### PR TITLE
Nzpmc 027/integrate query questions

### PR DESCRIPTION
**Pull request by ruby-oujo**
**Issue**

Integrated query questions into the sidebar component and selection process

**Risk**

Changes made to Exam.vue
- Also need to address possible deselection of questions

**Reviewers**

@Will-ZYS  @scorpionknifes

### CODE REVIEW

**Review by scorpionknifes — APPROVED** [review]
LTGM

**Review by matthewaptaylor — CHANGES_REQUESTED** [review]
It looks like you introduced breaking changes as the exam page now does not load... did you rebuild and make sure everything was working after you rebased? Or maybe it's just my computer? Screenshot attached.
Screenshot_20210701_211513

**Comment by scorpionknifes** [comment]
@matthewaptaylor I think you need the backend to be running. We probably should implement an error message when server connection fails

**Comment by matthewaptaylor** [comment]
> @matthewaptaylor I think you need the backend to be running. We probably should implement an error message when server connection fails

Maybe - the error is caused by it not being able to select an element in a component that it imports. Maybe the connection to the server is holding up the component from loading, which is why?

**Review by Will-ZYS — APPROVED** [review]
LGTM

**Review by scorpionknifes — APPROVED** [review]
LGTM

**Pull request merged**
