### PR TITLE
Nzpmc 010/implement single question component

### PR DESCRIPTION
**Pull request by lanxdrey19**
**Issue**

Single Question Component did not exist before

**Solution**

Implemented the Single Question Component

**Risk**

this branch originally had a conflict with master (with regards to src/views/Exam.vue) and master was merged to this branch locally.

**Reviewers**

@dtor068 
@scorpionknifes 
@ruby-oujo 
@Will-ZYS

### CODE REVIEW

**Review by matthewaptaylor — APPROVED** [review]
LGTM

**Review by Will-ZYS — APPROVED** [review]
LGTM

**Review by matthewaptaylor — APPROVED** [review]
lgtm

**Review by Will-ZYS — APPROVED** [review]
LGTM

**Review by ruby-oujo — COMMENTED** [review]
Nice job.

**Review by ruby-oujo — COMMENTED** [review]
Nice job

**Pull request merged**
