### PR TITLE
Nzpmc 024/setup apollo

### PR DESCRIPTION
**Pull request by Will-ZYS**
**Issue**

Apollo client needs to be setup in the frontend to fetch data

**Solution**

created apollo client and created queries, mutations, and fragments

**Risk**

more queries may need to be added in the future

**Reviewers**

### CODE REVIEW

**Review by lanxdrey19 — APPROVED** [review]
LGTM! :)

**Review by lanxdrey19 — APPROVED** [review]
lgtm! :)

**Comment by Kingston802** [comment]
LGTM!

**Review by Kingston802 — APPROVED** [review]
LGTM x 2

**Pull request merged**
