### PR TITLE
Nzpmc 043/flagged and answered indication

### PR DESCRIPTION
**Pull request by lanxdrey19**
**Issue**

Flagged and answered questions not implemented

**Solution**

Implemented features to let users know which questions they have flagged and answered

n/a

**Risk**

none known

**Reviewers**
@scorpionknifes 
@Will-ZYS 
@danieltorrey

### CODE REVIEW

**Review by scorpionknifes — DISMISSED** [review]
LGTM

**Comment by scorpionknifes** [comment]
@lanxdrey19 https://github.com/arnog/mathlive/issues/1135 bug report for new v0.69.5. Downgraded back to v0.69.4

**Review by scorpionknifes — APPROVED** [review]
LGTM

**Review by Will-ZYS — APPROVED** [review]
LGTM

**Pull request merged**
