### PR TITLE
Nzpmc 009/implement answer list component

### PR DESCRIPTION
**Pull request by lanxdrey19**
**Issue**

Answer List Component has not been implemented yet.

**Solution**

Answer List Component has been implemented. The Answer List Component contains Answer components.

**Risk**

None known

**Reviewers**

@Will-ZYS @scorpionknifes

### CODE REVIEW

**Comment by scorpionknifes** [comment]
Looks awesome 😄, can you add state logic where the user can only select one option e.g.
- Change colour + add tick when selected
- Only one option can be selected at once

TY

**Review by Will-ZYS — APPROVED** [review]
LGTM

**Comment by ruby-oujo** [comment]
Nice work, LGTMT

**Review by ruby-oujo — APPROVED** [review]
Nice work, LGTMT

**Pull request merged**
